# Pandas

In [2]:
# Creating a dataframe using  list inside a dictionary
import pandas as pd
reg = {'Roll_No':[1,2,3,4,5],'Name':['Shahnavas','Emmanual','Kevin','Sajad','Kiran'],'Score':[88,77,98,66,55]}
df = pd.DataFrame(reg)
df

   Roll_No       Name  Score
0        1  Shahnavas     88
1        2   Emmanual     77
2        3      Kevin     98
3        4      Sajad     66
4        5      Kiran     55

In [3]:
# Creating a Dataframe using tuple inside a list

reg = [(1,'Shahnavas',66),(2,'Emmanual',77),(3,'Kevin',66)]
df = pd.DataFrame(reg,columns=['Roll_no','Name','Score'])
df

   Roll_no       Name  Score
0        1  Shahnavas     66
1        2   Emmanual     77
2        3      Kevin     66

In [4]:
# Creating a Dataframe using dictionary inside a list

reg = [{'Roll_No':1,'Name':'Shahnavas','Score':77},
       {'Roll_No':2,'Name':'Emmanual','Score':77},
       {'Roll_No':3,'Name':'Kevin','Score':77}]
df = pd.DataFrame(reg)
df

   Roll_No       Name  Score
0        1  Shahnavas     77
1        2   Emmanual     77
2        3      Kevin     77

In [5]:
# Reading a csv file

df=pd.read_csv('01_Medical_insurance.csv')
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
2767   47  female  45.320         1     no  southeast   8569.86180
2768   21  female  34.600         0     no  southwest   2020.17700
2769   19    male  26.030         1    yes  northwest  16450.89470
2770   23    male  18.715         0     no  northwest  21595.38229
2771   54    male  31.600         0     no  southwest   9850.43200

[2772 rows x 7 columns]

In [6]:
type(df)

pandas.core.frame.DataFrame

# Series

In [111]:
data = [4,5,6,7]
ser = pd.Series(data)
ser

0    4
1    5
2    6
3    7
dtype: int64

In [9]:
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
2767   47  female  45.320         1     no  southeast   8569.86180
2768   21  female  34.600         0     no  southwest   2020.17700
2769   19    male  26.030         1    yes  northwest  16450.89470
2770   23    male  18.715         0     no  northwest  21595.38229
2771   54    male  31.600         0     no  southwest   9850.43200

[2772 rows x 7 columns]

In [10]:
type(df)

pandas.core.frame.DataFrame

In [11]:
age = df['age']
age

0       19
1       18
2       28
3       33
4       32
        ..
2767    47
2768    21
2769    19
2770    23
2771    54
Name: age, Length: 2772, dtype: int64

In [12]:
type(age)

pandas.core.series.Series

In [13]:
df=pd.read_csv('01_Medical_insurance.csv')
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
2767   47  female  45.320         1     no  southeast   8569.86180
2768   21  female  34.600         0     no  southwest   2020.17700
2769   19    male  26.030         1    yes  northwest  16450.89470
2770   23    male  18.715         0     no  northwest  21595.38229
2771   54    male  31.600         0     no  southwest   9850.43200

[2772 rows x 7 columns]

In [14]:
# Skiprows

df=pd.read_csv('01_Medical_insurance.csv',skiprows=[1,2,3,5])
df

      age     sex     bmi  children smoker     region      charges
0      33    male  22.705         0     no  northwest  21984.47061
1      31  female  25.740         0     no  southeast   3756.62160
2      46  female  33.440         1     no  southeast   8240.58960
3      37  female  27.740         3     no  northwest   7281.50560
4      37    male  29.830         2     no  northeast   6406.41070
...   ...     ...     ...       ...    ...        ...          ...
2763   47  female  45.320         1     no  southeast   8569.86180
2764   21  female  34.600         0     no  southwest   2020.17700
2765   19    male  26.030         1    yes  northwest  16450.89470
2766   23    male  18.715         0     no  northwest  21595.38229
2767   54    male  31.600         0     no  southwest   9850.43200

[2768 rows x 7 columns]

In [15]:
# names and header

df=pd.read_csv('01_Medical_insurance.csv',header=None,names=['a','b','c','d','e','f','g'])
df

        a       b       c         d       e          f            g
0     age     sex     bmi  children  smoker     region      charges
1      19  female    27.9         0     yes  southwest    16884.924
2      18    male   33.77         1      no  southeast    1725.5523
3      28    male      33         3      no  southeast     4449.462
4      33    male  22.705         0      no  northwest  21984.47061
...   ...     ...     ...       ...     ...        ...          ...
2768   47  female   45.32         1      no  southeast    8569.8618
2769   21  female    34.6         0      no  southwest     2020.177
2770   19    male   26.03         1     yes  northwest   16450.8947
2771   23    male  18.715         0      no  northwest  21595.38229
2772   54    male    31.6         0      no  southwest     9850.432

[2773 rows x 7 columns]

In [16]:
# Nrows

df=pd.read_csv('01_Medical_insurance.csv',nrows=100)
df

    age     sex     bmi  children smoker     region      charges
0    19  female  27.900         0    yes  southwest  16884.92400
1    18    male  33.770         1     no  southeast   1725.55230
2    28    male  33.000         3     no  southeast   4449.46200
3    33    male  22.705         0     no  northwest  21984.47061
4    32    male  28.880         0     no  northwest   3866.85520
..  ...     ...     ...       ...    ...        ...          ...
95   28  female  37.620         1     no  southeast   3766.88380
96   54  female  30.800         3     no  southwest  12105.32000
97   55    male  38.280         0     no  southeast  10226.28420
98   56    male  19.950         0    yes  northeast  22412.64850
99   38    male  19.300         0    yes  southwest  15820.69900

[100 rows x 7 columns]

In [17]:
# navalues
df=pd.read_csv('01_Medical_insurance.csv',na_values=[0])
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900       NaN    yes  southwest  16884.92400
1      18    male  33.770       1.0     no  southeast   1725.55230
2      28    male  33.000       3.0     no  southeast   4449.46200
3      33    male  22.705       NaN     no  northwest  21984.47061
4      32    male  28.880       NaN     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
2767   47  female  45.320       1.0     no  southeast   8569.86180
2768   21  female  34.600       NaN     no  southwest   2020.17700
2769   19    male  26.030       1.0    yes  northwest  16450.89470
2770   23    male  18.715       NaN     no  northwest  21595.38229
2771   54    male  31.600       NaN     no  southwest   9850.43200

[2772 rows x 7 columns]

In [18]:
df=pd.read_csv('01_Medical_insurance.csv',na_values={'children':[0],'smoker':['no']})
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900       NaN    yes  southwest  16884.92400
1      18    male  33.770       1.0    NaN  southeast   1725.55230
2      28    male  33.000       3.0    NaN  southeast   4449.46200
3      33    male  22.705       NaN    NaN  northwest  21984.47061
4      32    male  28.880       NaN    NaN  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
2767   47  female  45.320       1.0    NaN  southeast   8569.86180
2768   21  female  34.600       NaN    NaN  southwest   2020.17700
2769   19    male  26.030       1.0    yes  northwest  16450.89470
2770   23    male  18.715       NaN    NaN  northwest  21595.38229
2771   54    male  31.600       NaN    NaN  southwest   9850.43200

[2772 rows x 7 columns]

In [19]:
# converters

df=pd.read_csv('01_Medical_insurance.csv')
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
2767   47  female  45.320         1     no  southeast   8569.86180
2768   21  female  34.600         0     no  southwest   2020.17700
2769   19    male  26.030         1    yes  northwest  16450.89470
2770   23    male  18.715         0     no  northwest  21595.38229
2771   54    male  31.600         0     no  southwest   9850.43200

[2772 rows x 7 columns]

In [20]:
def conv(x):
    if x=='yes':
        return 1
    else:
        return 0

df=pd.read_csv('01_Medical_insurance.csv',converters={'smoker':conv})
df

      age     sex     bmi  children  smoker     region      charges
0      19  female  27.900         0       1  southwest  16884.92400
1      18    male  33.770         1       0  southeast   1725.55230
2      28    male  33.000         3       0  southeast   4449.46200
3      33    male  22.705         0       0  northwest  21984.47061
4      32    male  28.880         0       0  northwest   3866.85520
...   ...     ...     ...       ...     ...        ...          ...
2767   47  female  45.320         1       0  southeast   8569.86180
2768   21  female  34.600         0       0  southwest   2020.17700
2769   19    male  26.030         1       1  northwest  16450.89470
2770   23    male  18.715         0       0  northwest  21595.38229
2771   54    male  31.600         0       0  southwest   9850.43200

[2772 rows x 7 columns]

## Basic function in pandas

In [22]:
# Shape
df.shape

(2772, 7)

In [23]:
df.head(10)

   age     sex     bmi  children  smoker     region      charges
0   19  female  27.900         0       1  southwest  16884.92400
1   18    male  33.770         1       0  southeast   1725.55230
2   28    male  33.000         3       0  southeast   4449.46200
3   33    male  22.705         0       0  northwest  21984.47061
4   32    male  28.880         0       0  northwest   3866.85520
5   31  female  25.740         0       0  southeast   3756.62160
6   46  female  33.440         1       0  southeast   8240.58960
7   37  female  27.740         3       0  northwest   7281.50560
8   37    male  29.830         2       0  northeast   6406.41070
9   60  female  25.840         0       0  northwest  28923.13692

In [24]:
df.tail(10)

      age     sex     bmi  children  smoker     region      charges
2762   21  female  32.680         2       0  northwest  26018.95052
2763   51    male  37.000         0       0  southwest   8798.59300
2764   22  female  31.020         3       1  southeast  35595.58980
2765   47    male  36.080         1       1  southeast  42211.13820
2766   18    male  23.320         1       0  southeast   1711.02680
2767   47  female  45.320         1       0  southeast   8569.86180
2768   21  female  34.600         0       0  southwest   2020.17700
2769   19    male  26.030         1       1  northwest  16450.89470
2770   23    male  18.715         0       0  northwest  21595.38229
2771   54    male  31.600         0       0  southwest   9850.43200

In [25]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

### slicing dataframe

In [27]:
df[['age','sex']][:100]

    age     sex
0    19  female
1    18    male
2    28    male
3    33    male
4    32    male
..  ...     ...
95   28  female
96   54  female
97   55    male
98   56    male
99   38    male

[100 rows x 2 columns]

In [28]:
df

      age     sex     bmi  children  smoker     region      charges
0      19  female  27.900         0       1  southwest  16884.92400
1      18    male  33.770         1       0  southeast   1725.55230
2      28    male  33.000         3       0  southeast   4449.46200
3      33    male  22.705         0       0  northwest  21984.47061
4      32    male  28.880         0       0  northwest   3866.85520
...   ...     ...     ...       ...     ...        ...          ...
2767   47  female  45.320         1       0  southeast   8569.86180
2768   21  female  34.600         0       0  southwest   2020.17700
2769   19    male  26.030         1       1  northwest  16450.89470
2770   23    male  18.715         0       0  northwest  21595.38229
2771   54    male  31.600         0       0  southwest   9850.43200

[2772 rows x 7 columns]

In [29]:
df.set_index('age')

        sex     bmi  children  smoker     region      charges
age
19   female  27.900         0       1  southwest  16884.92400
18     male  33.770         1       0  southeast   1725.55230
28     male  33.000         3       0  southeast   4449.46200
33     male  22.705         0       0  northwest  21984.47061
32     male  28.880         0       0  northwest   3866.85520
..      ...     ...       ...     ...        ...          ...
47   female  45.320         1       0  southeast   8569.86180
21   female  34.600         0       0  southwest   2020.17700
19     male  26.030         1       1  northwest  16450.89470
23     male  18.715         0       0  northwest  21595.38229
54     male  31.600         0       0  southwest   9850.43200

[2772 rows x 6 columns]

In [30]:
df.sort_values('age',ascending=False)

      age     sex     bmi  children  smoker     region      charges
2050   64  female  22.990         0       1  southeast  27037.91410
378    64  female  30.115         3       0  northwest  16455.70785
1714   64  female  33.800         1       1  southwest  47928.03000
420    64    male  33.880         0       1  southeast  46889.26120
335    64    male  34.500         0       0  southwest  13822.80300
...   ...     ...     ...       ...     ...        ...          ...
1334   18  female  31.920         0       0  northeast   2205.98080
1317   18    male  53.130         0       0  southeast   1163.46270
1315   18    male  28.310         1       0  northeast  11272.33139
1296   18    male  26.125         0       0  northeast   1708.92575
2634   18  female  39.820         0       0  southeast   1633.96180

[2772 rows x 7 columns]

In [31]:
df['age'].min()

18

In [32]:
df['age'].max()

64

In [33]:
df['age'].mean()

39.10966810966811

In [34]:
df['age'].std()

14.081459420836477

In [35]:
df.describe()

               age          bmi     children       smoker       charges
count  2772.000000  2772.000000  2772.000000  2772.000000   2772.000000
mean     39.109668    30.701349     1.101732     0.203463  13261.369959
std      14.081459     6.129449     1.214806     0.402647  12151.768945
min      18.000000    15.960000     0.000000     0.000000   1121.873900
25%      26.000000    26.220000     0.000000     0.000000   4687.797000
50%      39.000000    30.447500     1.000000     0.000000   9333.014350
75%      51.000000    34.770000     2.000000     0.000000  16577.779500
max      64.000000    53.130000     5.000000     1.000000  63770.428010

### Conditional Selecting

In [37]:
df

      age     sex     bmi  children  smoker     region      charges
0      19  female  27.900         0       1  southwest  16884.92400
1      18    male  33.770         1       0  southeast   1725.55230
2      28    male  33.000         3       0  southeast   4449.46200
3      33    male  22.705         0       0  northwest  21984.47061
4      32    male  28.880         0       0  northwest   3866.85520
...   ...     ...     ...       ...     ...        ...          ...
2767   47  female  45.320         1       0  southeast   8569.86180
2768   21  female  34.600         0       0  southwest   2020.17700
2769   19    male  26.030         1       1  northwest  16450.89470
2770   23    male  18.715         0       0  northwest  21595.38229
2771   54    male  31.600         0       0  southwest   9850.43200

[2772 rows x 7 columns]

In [38]:
df[df['age']>50]

      age     sex     bmi  children  smoker     region      charges
9      60  female  25.840         0       0  northwest  28923.13692
11     62  female  26.290         0       1  southeast  27808.72510
13     56  female  39.820         0       0  southeast  11090.71780
16     52  female  30.780         1       0  northeast  10797.33620
18     56    male  40.300         0       0  southwest  10602.38500
...   ...     ...     ...       ...     ...        ...          ...
2754   59  female  27.500         0       0  southwest  12233.82800
2758   53    male  29.480         0       0  southeast   9487.64420
2761   54  female  35.815         3       0  northwest  12495.29085
2763   51    male  37.000         0       0  southwest   8798.59300
2771   54    male  31.600         0       0  southwest   9850.43200

[738 rows x 7 columns]

### Filing null values

In [40]:
import pandas as pd
df = pd.read_csv('high_popularity_spotify_data.csv')
df

,energy,tempo,danceability,playlist_genre,loudness,liveness,valence,track_artist,time_signature,speechiness,...,instrumentalness,track_album_id,mode,key,duration_ms,acousticness,id,playlist_subgenre,type,playlist_id
0,0.592,157.969,0.521,pop,-7.777,0.1220,0.535,"Lady Gaga, Bruno Mars",3,0.0304,...,0.000000,10FLjwfpbxLmW8c25Xyc2N,0,6,251668,0.3080,2plbrEY59IikOBgBGLjaoe,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
1,0.507,104.978,0.747,pop,-10.171,0.1170,0.438,Billie Eilish,4,0.0358,...,0.060800,7aJuG4TFXa2hmE4z1yxc3n,1,2,210373,0.2000,6dOtVTDdiauQNBQEDOtlAB,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
2,0.808,108.548,0.554,pop,-4.169,0.1590,0.372,Gracie Abrams,4,0.0368,...,0.000000,0hBRqPYPXhr1RkTDG3n4Mk,1,1,166300,0.2140,7ne4VBA60CxGM75vw0EYad,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
3,0.910,112.966,0.670,pop,-4.070,0.3040,0.786,Sabrina Carpenter,4,0.0634,...,0.000000,4B4Elma4nNDUyl6D5PvQkj,0,0,157280,0.0939,1d7Ptw3qYcfpdLNL5REhtJ,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
4,0.783,149.027,0.777,pop,-4.477,0.3550,0.939,"ROSÉ, Bruno Mars",4,0.2600,...,0.000000,2IYQwwgxgOIn7t3iF6ufFD,0,0,169917,0.0283,5vNRhkKd0yEAg8suGBpjeY,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1681,0.422,124.357,0.573,latin,-7.621,0.1020,0.693,Libianca,5,0.0678,...,0.000013,5Hmh6N8oisrcuZKa8EY5dn,0,10,184791,0.5510,26b3oVLrRUaaybJulow9kz,afro-latin,audio_features,0oU30cCr8klmMsuOKHDLkh
1682,0.725,105.016,0.711,latin,-8.315,0.1100,0.530,Omah Lay,4,0.0941,...,0.129000,5NLjxx8nRy9ooUmgpOvfem,0,3,183057,0.4240,1wADwLSkYhrSmy4vdy6BRn,afro-latin,audio_features,0oU30cCr8klmMsuOKHDLkh
1683,0.809,99.005,0.724,latin,-5.022,0.0765,0.606,"Davido, FAVE",4,0.0929,...,0.000000,6lI21W76LD0S3vC55GrfSS,0,6,194040,0.1820,7vKXc90NT5WBm3UTT4iTVG,afro-latin,audio_features,0oU30cCr8klmMsuOKHDLkh
1684,0.642,83.389,0.463,latin,-4.474,0.0686,0.339,"Future, Drake, Tems",4,0.3400,...,0.000000,6tE9Dnp2zInFij4jKssysL,1,1,189893,0.3140,59nOXPmaKlBfGMDeOVGrIK,afro-latin,audio_features,0oU30cCr8klmMsuOKHDLkh
1685,0.890,126.881,0.645,pop,-4.985,0.3760,0.421,"Alan Walker, Ina Wroldsen",4,0.1280,...,0.000009,34yBJhr8zlBAHMEMSwrISN,1,6,205087,0.2590,2GE3k8I0Sbh0puCjI15KGy,scandi,audio_features,59z06GgF6TTDbm5cr1RZUC

In [41]:
# checking null values in dataset
df.isnull().sum()

energy                      0
tempo                       0
danceability                0
playlist_genre              0
loudness                    0
liveness                    0
valence                     0
track_artist                0
time_signature              0
speechiness                 0
track_popularity            0
track_href                  0
uri                         0
track_album_name            1
playlist_name               0
analysis_url                0
track_id                    0
track_name                  0
track_album_release_date    0
instrumentalness            0
track_album_id              0
mode                        0
key                         0
duration_ms                 0
acousticness                0
id                          0
playlist_subgenre           0
type                        0
playlist_id                 0
dtype: int64

In [42]:
df['track_album_name'] = df['track_album_name'].fillna('nil')

In [43]:
df.isnull().sum()

energy                      0
tempo                       0
danceability                0
playlist_genre              0
loudness                    0
liveness                    0
valence                     0
track_artist                0
time_signature              0
speechiness                 0
track_popularity            0
track_href                  0
uri                         0
track_album_name            0
playlist_name               0
analysis_url                0
track_id                    0
track_name                  0
track_album_release_date    0
instrumentalness            0
track_album_id              0
mode                        0
key                         0
duration_ms                 0
acousticness                0
id                          0
playlist_subgenre           0
type                        0
playlist_id                 0
dtype: int64

In [44]:
# dropna - dropping the row with null values

In [45]:
# Checking for duplicates

df.duplicated().sum()

0

In [46]:
# Handling Duplicate records

df.drop_duplicates(inplace=True)

In [47]:
# replace

df

,energy,tempo,danceability,playlist_genre,loudness,liveness,valence,track_artist,time_signature,speechiness,...,instrumentalness,track_album_id,mode,key,duration_ms,acousticness,id,playlist_subgenre,type,playlist_id
0,0.592,157.969,0.521,pop,-7.777,0.1220,0.535,"Lady Gaga, Bruno Mars",3,0.0304,...,0.000000,10FLjwfpbxLmW8c25Xyc2N,0,6,251668,0.3080,2plbrEY59IikOBgBGLjaoe,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
1,0.507,104.978,0.747,pop,-10.171,0.1170,0.438,Billie Eilish,4,0.0358,...,0.060800,7aJuG4TFXa2hmE4z1yxc3n,1,2,210373,0.2000,6dOtVTDdiauQNBQEDOtlAB,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
2,0.808,108.548,0.554,pop,-4.169,0.1590,0.372,Gracie Abrams,4,0.0368,...,0.000000,0hBRqPYPXhr1RkTDG3n4Mk,1,1,166300,0.2140,7ne4VBA60CxGM75vw0EYad,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
3,0.910,112.966,0.670,pop,-4.070,0.3040,0.786,Sabrina Carpenter,4,0.0634,...,0.000000,4B4Elma4nNDUyl6D5PvQkj,0,0,157280,0.0939,1d7Ptw3qYcfpdLNL5REhtJ,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
4,0.783,149.027,0.777,pop,-4.477,0.3550,0.939,"ROSÉ, Bruno Mars",4,0.2600,...,0.000000,2IYQwwgxgOIn7t3iF6ufFD,0,0,169917,0.0283,5vNRhkKd0yEAg8suGBpjeY,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1681,0.422,124.357,0.573,latin,-7.621,0.1020,0.693,Libianca,5,0.0678,...,0.000013,5Hmh6N8oisrcuZKa8EY5dn,0,10,184791,0.5510,26b3oVLrRUaaybJulow9kz,afro-latin,audio_features,0oU30cCr8klmMsuOKHDLkh
1682,0.725,105.016,0.711,latin,-8.315,0.1100,0.530,Omah Lay,4,0.0941,...,0.129000,5NLjxx8nRy9ooUmgpOvfem,0,3,183057,0.4240,1wADwLSkYhrSmy4vdy6BRn,afro-latin,audio_features,0oU30cCr8klmMsuOKHDLkh
1683,0.809,99.005,0.724,latin,-5.022,0.0765,0.606,"Davido, FAVE",4,0.0929,...,0.000000,6lI21W76LD0S3vC55GrfSS,0,6,194040,0.1820,7vKXc90NT5WBm3UTT4iTVG,afro-latin,audio_features,0oU30cCr8klmMsuOKHDLkh
1684,0.642,83.389,0.463,latin,-4.474,0.0686,0.339,"Future, Drake, Tems",4,0.3400,...,0.000000,6tE9Dnp2zInFij4jKssysL,1,1,189893,0.3140,59nOXPmaKlBfGMDeOVGrIK,afro-latin,audio_features,0oU30cCr8klmMsuOKHDLkh
1685,0.890,126.881,0.645,pop,-4.985,0.3760,0.421,"Alan Walker, Ina Wroldsen",4,0.1280,...,0.000009,34yBJhr8zlBAHMEMSwrISN,1,6,205087,0.2590,2GE3k8I0Sbh0puCjI15KGy,scandi,audio_features,59z06GgF6TTDbm5cr1RZUC

In [48]:
df['time_signature'] = df['time_signature'].replace({3:'three',4:'four',5:'five'})

In [49]:
df

,energy,tempo,danceability,playlist_genre,loudness,liveness,valence,track_artist,time_signature,speechiness,...,instrumentalness,track_album_id,mode,key,duration_ms,acousticness,id,playlist_subgenre,type,playlist_id
0,0.592,157.969,0.521,pop,-7.777,0.1220,0.535,"Lady Gaga, Bruno Mars",three,0.0304,...,0.000000,10FLjwfpbxLmW8c25Xyc2N,0,6,251668,0.3080,2plbrEY59IikOBgBGLjaoe,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
1,0.507,104.978,0.747,pop,-10.171,0.1170,0.438,Billie Eilish,four,0.0358,...,0.060800,7aJuG4TFXa2hmE4z1yxc3n,1,2,210373,0.2000,6dOtVTDdiauQNBQEDOtlAB,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
2,0.808,108.548,0.554,pop,-4.169,0.1590,0.372,Gracie Abrams,four,0.0368,...,0.000000,0hBRqPYPXhr1RkTDG3n4Mk,1,1,166300,0.2140,7ne4VBA60CxGM75vw0EYad,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
3,0.910,112.966,0.670,pop,-4.070,0.3040,0.786,Sabrina Carpenter,four,0.0634,...,0.000000,4B4Elma4nNDUyl6D5PvQkj,0,0,157280,0.0939,1d7Ptw3qYcfpdLNL5REhtJ,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
4,0.783,149.027,0.777,pop,-4.477,0.3550,0.939,"ROSÉ, Bruno Mars",four,0.2600,...,0.000000,2IYQwwgxgOIn7t3iF6ufFD,0,0,169917,0.0283,5vNRhkKd0yEAg8suGBpjeY,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1681,0.422,124.357,0.573,latin,-7.621,0.1020,0.693,Libianca,five,0.0678,...,0.000013,5Hmh6N8oisrcuZKa8EY5dn,0,10,184791,0.5510,26b3oVLrRUaaybJulow9kz,afro-latin,audio_features,0oU30cCr8klmMsuOKHDLkh
1682,0.725,105.016,0.711,latin,-8.315,0.1100,0.530,Omah Lay,four,0.0941,...,0.129000,5NLjxx8nRy9ooUmgpOvfem,0,3,183057,0.4240,1wADwLSkYhrSmy4vdy6BRn,afro-latin,audio_features,0oU30cCr8klmMsuOKHDLkh
1683,0.809,99.005,0.724,latin,-5.022,0.0765,0.606,"Davido, FAVE",four,0.0929,...,0.000000,6lI21W76LD0S3vC55GrfSS,0,6,194040,0.1820,7vKXc90NT5WBm3UTT4iTVG,afro-latin,audio_features,0oU30cCr8klmMsuOKHDLkh
1684,0.642,83.389,0.463,latin,-4.474,0.0686,0.339,"Future, Drake, Tems",four,0.3400,...,0.000000,6tE9Dnp2zInFij4jKssysL,1,1,189893,0.3140,59nOXPmaKlBfGMDeOVGrIK,afro-latin,audio_features,0oU30cCr8klmMsuOKHDLkh
1685,0.890,126.881,0.645,pop,-4.985,0.3760,0.421,"Alan Walker, Ina Wroldsen",four,0.1280,...,0.000009,34yBJhr8zlBAHMEMSwrISN,1,6,205087,0.2590,2GE3k8I0Sbh0puCjI15KGy,scandi,audio_features,59z06GgF6TTDbm5cr1RZUC

### Group By

In [51]:
df

,energy,tempo,danceability,playlist_genre,loudness,liveness,valence,track_artist,time_signature,speechiness,...,instrumentalness,track_album_id,mode,key,duration_ms,acousticness,id,playlist_subgenre,type,playlist_id
0,0.592,157.969,0.521,pop,-7.777,0.1220,0.535,"Lady Gaga, Bruno Mars",three,0.0304,...,0.000000,10FLjwfpbxLmW8c25Xyc2N,0,6,251668,0.3080,2plbrEY59IikOBgBGLjaoe,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
1,0.507,104.978,0.747,pop,-10.171,0.1170,0.438,Billie Eilish,four,0.0358,...,0.060800,7aJuG4TFXa2hmE4z1yxc3n,1,2,210373,0.2000,6dOtVTDdiauQNBQEDOtlAB,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
2,0.808,108.548,0.554,pop,-4.169,0.1590,0.372,Gracie Abrams,four,0.0368,...,0.000000,0hBRqPYPXhr1RkTDG3n4Mk,1,1,166300,0.2140,7ne4VBA60CxGM75vw0EYad,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
3,0.910,112.966,0.670,pop,-4.070,0.3040,0.786,Sabrina Carpenter,four,0.0634,...,0.000000,4B4Elma4nNDUyl6D5PvQkj,0,0,157280,0.0939,1d7Ptw3qYcfpdLNL5REhtJ,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
4,0.783,149.027,0.777,pop,-4.477,0.3550,0.939,"ROSÉ, Bruno Mars",four,0.2600,...,0.000000,2IYQwwgxgOIn7t3iF6ufFD,0,0,169917,0.0283,5vNRhkKd0yEAg8suGBpjeY,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1681,0.422,124.357,0.573,latin,-7.621,0.1020,0.693,Libianca,five,0.0678,...,0.000013,5Hmh6N8oisrcuZKa8EY5dn,0,10,184791,0.5510,26b3oVLrRUaaybJulow9kz,afro-latin,audio_features,0oU30cCr8klmMsuOKHDLkh
1682,0.725,105.016,0.711,latin,-8.315,0.1100,0.530,Omah Lay,four,0.0941,...,0.129000,5NLjxx8nRy9ooUmgpOvfem,0,3,183057,0.4240,1wADwLSkYhrSmy4vdy6BRn,afro-latin,audio_features,0oU30cCr8klmMsuOKHDLkh
1683,0.809,99.005,0.724,latin,-5.022,0.0765,0.606,"Davido, FAVE",four,0.0929,...,0.000000,6lI21W76LD0S3vC55GrfSS,0,6,194040,0.1820,7vKXc90NT5WBm3UTT4iTVG,afro-latin,audio_features,0oU30cCr8klmMsuOKHDLkh
1684,0.642,83.389,0.463,latin,-4.474,0.0686,0.339,"Future, Drake, Tems",four,0.3400,...,0.000000,6tE9Dnp2zInFij4jKssysL,1,1,189893,0.3140,59nOXPmaKlBfGMDeOVGrIK,afro-latin,audio_features,0oU30cCr8klmMsuOKHDLkh
1685,0.890,126.881,0.645,pop,-4.985,0.3760,0.421,"Alan Walker, Ina Wroldsen",four,0.1280,...,0.000009,34yBJhr8zlBAHMEMSwrISN,1,6,205087,0.2590,2GE3k8I0Sbh0puCjI15KGy,scandi,audio_features,59z06GgF6TTDbm5cr1RZUC

In [52]:
# Returing all the categories in a categorical column
df['playlist_genre'].unique()

array(['pop', 'rock', 'jazz', 'classical', 'hip-hop', 'afrobeats',
       'latin', 'indian', 'country', 'r&b', 'electronic', 'soul',
       'gaming', 'j-pop', 'metal', 'reggae', 'k-pop', 'arabic', 'punk',
       'blues', 'folk', 'lofi', 'brazilian', 'turkish', 'ambient',
       'korean', 'world', 'indie'], dtype=object)

In [53]:
# Returing the count of all categories in a categorical column
df['playlist_genre'].nunique()

28

In [54]:
# Absolute Frequency of a categorical column

df['playlist_genre'].value_counts()

playlist_genre
pop           357
rock          235
hip-hop       227
latin         184
electronic    148
gaming        100
ambient        61
punk           50
arabic         50
r&b            50
blues          45
metal          35
folk           33
afrobeats      20
brazilian      14
j-pop          11
k-pop          11
classical      10
indian          9
korean          8
turkish         7
reggae          5
world           4
indie           4
country         3
soul            2
lofi            2
jazz            1
Name: count, dtype: int64

In [55]:
df_play_list = df.groupby('playlist_genre')

In [56]:
df_play_list.get_group('punk')

,energy,tempo,danceability,playlist_genre,loudness,liveness,valence,track_artist,time_signature,speechiness,...,instrumentalness,track_album_id,mode,key,duration_ms,acousticness,id,playlist_subgenre,type,playlist_id
1129,0.776,77.987,0.585,punk,-5.898,0.3000,0.4270,Avril Lavigne,four,0.0459,...,0.000008,3zXjR3y2dUWklKmmp6lEhy,1,5,244507,0.057200,5xEM5hIgJ1jjgcEBfpkt2F,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1130,0.954,143.850,0.465,punk,-4.251,0.5730,0.4580,The All-American Rejects,four,0.0440,...,0.000005,3PWEGZ6CYvXRnr0JCECsDe,1,10,193653,0.000346,5lDriBxJd22IhOH9zTcFrV,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1131,0.849,162.152,0.643,punk,-5.428,0.0580,0.9030,Jimmy Eat World,four,0.0526,...,0.000000,0UJhhj5bn5AGAjryFnhueP,1,2,165853,0.037100,6GG73Jik4jUlQCkKg9JuGO,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1132,0.691,100.008,0.718,punk,-6.440,0.0627,0.5520,The All-American Rejects,four,0.0387,...,0.000000,3BCMpDOcQlbCZpf5vnTadZ,1,4,213107,0.015900,6ihL9TjfRjadfEePzXXyVF,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1133,0.887,119.974,0.606,punk,-4.404,0.3370,0.9030,Bowling For Soup,four,0.0598,...,0.000000,43jBR9MNJk5AUuB56M0pRF,1,4,193000,0.000242,5oQcOu1omDykbIPSdSQQNJ,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1134,0.750,118.015,0.774,punk,-4.927,0.0808,0.9270,Fountains Of Wayne,four,0.0412,...,0.000018,6TZp52tXShLQbq8yNMxqNT,0,11,197987,0.002070,27L8sESb3KR79asDUBu8nW,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1135,0.906,172.977,0.517,punk,-3.677,0.1130,0.7310,Paramore,four,0.0735,...,0.000009,71rziY9eLo1tA2dBMxrwhc,1,1,211520,0.002720,6SpLc7EXZIPpy0sVko0aoU,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1136,0.883,93.410,0.450,punk,-4.094,0.2930,0.3280,Evanescence,four,0.0524,...,0.000000,3lFQ9ihSNR5YD0yi0yTzdC,1,7,214707,0.001930,663Karu2rvKLdnY0eo1n3M,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1137,0.900,149.937,0.487,punk,-4.417,0.3580,0.4840,Avril Lavigne,four,0.0482,...,0.000000,3zXjR3y2dUWklKmmp6lEhy,1,0,204000,0.000068,00Mb3DuaIH1kjrwOku9CGU,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1138,0.406,151.950,0.457,punk,-7.462,0.1170,0.2080,Avril Lavigne,three,0.0291,...,0.000000,3zXjR3y2dUWklKmmp6lEhy,1,9,223067,0.080000,1jlG3KJ3gdYmhfuySFfpO1,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1139,0.936,170.229,0.414,punk,-2.407,0.3690,0.7400,Avril Lavigne,four,0.0758,...,0.000000,7851Vsjv3apS52sXUik6iF,1,2,242413,0.001360,6sqNctd7MlJoKDOxPVCAvU,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1140,0.939,177.751,0.494,punk,-3.127,0.1390,0.8930,Good Charlotte,four,0.1260,...,0.000000,5CTygC3aONv7l0klY4k3hc,1,1,175093,0.006660,0BRHnOFm6sjxN1i9LJrUDu,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1141,0.893,104.031,0.610,punk,-3.681,0.0210,0.6730,Paramore,four,0.0921,...,0.000044,4sgYpkIASM1jVlNC8Wp9oF,1,9,296520,0.154000,1j8z4TTjJ1YOdoFEDwJTQa,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1142,0.923,136.010,0.602,punk,-3.763,0.0561,0.7650,Paramore,four,0.0440,...,0.000000,4sgYpkIASM1jVlNC8Wp9oF,1,5,216013,0.009800,1yjY7rpaAQvKwpdUliHx0d,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1143,0.830,170.094,0.569,punk,-4.106,0.1140,0.6090,Panic! At The Disco,four,0.1400,...,0.000000,2YeOhhJg3OWpN0F1VYPxtW,0,9,186635,0.080700,4bPQs0PHn4xbipzdPfn6du,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1144,0.897,148.708,0.434,punk,-4.918,0.6120,0.6850,blink-182,four,0.0488,...,0.000000,652N05EcNH1a4bIlUixQE2,1,0,167067,0.010300,2m1hi0nfMR9vdGC8UcrnwU,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1145,0.814,104.980,0.546,punk,-5.146,0.0972,0.1460,Green Day,four,0.0314,...,0.000000,5dN7F9DV0Qg1XRdIgW8rke,1,7,285653,0.023000,3ZffCQKLFLUvYM59XKLbVm,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1146,0.943,94.612,0.331,punk,-3.188,0.2420,0.2960,Evanescence,four,0.0698,...,0.000002,02w1xMzzdF2OJxTeh1basm,0,4,235893,0.007210,0COqiPhxzoWICwFCS4eZcp,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1147,0.926,149.976,0.578,punk,-3.689,0.1400,0.8770,Avril Lavigne,four,0.0548,...,0.012700,1COPJyU2PpM2Itcob3vhFF,0,6,220707,0.004720,2z4U9d5OAA4YLNXoCgioxo,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1148,0.781,110.024,0.655,punk,-6.547,0.0867,0.5840,blink-182,four,0.0340,...,0.000005,6DMUAqxiFfLdqXv0vqcrQA,1,11,227240,0.001030,1oTo3ijRbaDAtrjJrGAPSw,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1149,0.682,167.060,0.496,punk,-4.095,0.0589,0.4740,Green Day,four,0.0294,...,0.000029,3id4t9IqRoB1f1smOERtrY,1,8,262333,0.005520,5GorCbAP4aL0EJ16frG2hd,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1150,0.988,186.113,0.380,punk,-2.042,0.3680,0.7690,Green Day,four,0.0639,...,0.000079,5dN7F9DV0Qg1XRdIgW8rke,1,1,176346,0.000026,6nTiIhLmQ3FWhvrGafw2zj,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1151,0.823,87.904,0.693,punk,-3.761,0.3280,0.7410,Weezer,four,0.0726,...,0.000000,4D8A8M0NJjEdQhusawyeDz,1,5,196093,0.093200,1yKu2MhpwzDXXH2tzG6xoa,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1152,0.563,137.715,0.452,punk,-6.607,0.1430,0.2090,Paramore,three,0.0272,...,0.000000,27UqZoE1kV6sIV6uQcI28A,1,4,267653,0.144000,7JIuqL4ZqkpfGKQhYlrirs,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1153,0.744,119.921,0.628,punk,-4.718,0.3130,0.2770,"mgk, YUNGBLUD, Travis Barker",four,0.0379,...,0.000000,0bJIHF1Or1YBLFBMwv53K2,1,7,169397,0.025700,2gTdDMpNxIRFSiu7HutMCg,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1154,0.946,103.408,0.494,punk,-2.757,0.3980,0.7410,Lit,four,0.0637,...,0.000000,3w5Uz3q4SJze14P60ZChsp,1,4,169027,0.001290,33iv3wnGMrrDugd7GBso1z,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1155,0.904,173.734,0.486,punk,-3.751,0.0947,0.7860,Yellowcard,four,0.0638,...,0.000028,24IBCzEJlHBI0ioxlSuSPA,0,6,198267,0.000034,23oxJmDc1V9uLUSmN2LIvx,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1156,0.932,92.956,0.545,punk,-2.189,0.1270,0.4640,The Red Jumpsuit Apparatus,four,0.0399,...,0.000000,6TyPSzd5rA2rQ9yLJJ1Gg2,0,7,192000,0.000665,4wzjNqjKAKDU82e8uMhzmr,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1157,0.873,143.519,0.308,punk,-4.542,0.0974,0.6860,AFI,four,0.0533,...,0.000729,1XcA7EEpVRg3FpVbhWu9JV,1,8,206587,0.000220,0Ti2dlF2xLjXblvdU5fCxM,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1158,0.892,154.844,0.460,punk,-5.046,0.1060,0.5900,Fall Out Boy,four,0.0619,...,0.000000,0hHopYqXhuvYSHtVyrcb1g,0,10,203507,0.005100,3Zwu2K0Qa5sT6teCCHPShP,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1159,0.857,111.647,0.463,punk,-3.063,0.1840,0.8560,My Chemical Romance,four,0.0632,...,0.000000,0FZK97MXMm5mUQ8mtudjuK,1,4,161920,0.050600,7j31rVgGX9Q2blT92VBEA0,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1160,0.914,196.482,0.403,punk,-5.215,0.0650,0.6260,Sum 41,four,0.1420,...,0.000000,2UCWsnmZEVg9HhnMeKTsim,1,9,178267,0.000579,4KacUpvbA3Mfo05gttTjhN,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1161,0.951,157.663,0.391,punk,-7.419,0.0878,0.4680,blink-182,four,0.0688,...,0.000446,652N05EcNH1a4bIlUixQE2,1,6,148360,0.012000,4LJhJ6DQS7NwE7UKtvcM52,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1162,0.705,138.559,0.818,punk,-6.679,0.6130,0.7720,Gorillaz,four,0.1770,...,0.002330,0bUTHlWbkSQysoM3VsWldT,1,6,222640,0.008360,0d28khcov6AiegSCpG5TuT,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1163,0.940,179.722,0.210,punk,-3.427,0.2690,0.2550,My Chemical Romance,four,0.1230,...,0.000000,3DuiGV3J09SUhvp8gqNx8h,1,9,186480,0.006020,7lRlq939cDG4SzWOF4VAnd,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1164,0.870,164.057,0.280,punk,-4.219,0.1010,0.2840,Paramore,four,0.0592,...,0.006080,70iJhodSPkl7FR1VW4n0KF,0,10,261960,0.000686,1ZLtE9tSJdaUiIJ9YoKHQe,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1165,0.818,119.965,0.695,punk,-5.379,0.0219,0.9160,Paramore,four,0.0334,...,0.000005,1c9Sx7XdXuMptGyfCB6hHs,0,5,182693,0.006470,0w5Bdu51Ka25Pf3hojsKHh,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1166,0.960,125.921,0.356,punk,-3.487,0.2090,0.0857,My Chemical Romance,four,0.1040,...,0.000000,3DuiGV3J09SUhvp8gqNx8h,1,4,204733,0.014200,5dTHtzHFPyi8TlTtzoz1J9,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1167,0.883,122.252,0.467,punk,-3.679,0.1250,0.3090,My Chemical Romance,four,0.1060,...,0.000152,0FZK97MXMm5mUQ8mtudjuK,0,2,299227,0.000321,2d6m2F4I7wCuAKtSsdhh83,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1168,0.986,165.981,0.411,punk,-2.522,0.3710,0.6490,My Chemical Romance,four,0.0583,...,0.001480,2wPnKggTK3QhYAKL7Q0vvr,0,8,205960,0.000264,5BB0Jzw60KyfSTyjJqtely,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1169,0.796,169.835,0.289,punk,-4.220,0.2020,0.3300,My Chemical Romance,four,0.0494,...,0.000026,0FZK97MXMm5mUQ8mtudjuK,1,0,238680,0.008370,4RAOI1etsgbh5NP3T5R8rN,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1170,0.886,145.781,0.202,punk,-3.805,0.6430,0.1920,My Chemical Romance,four,0.0816,...,0.000000,3DuiGV3J09SUhvp8gqNx8h,0,11,194253,0.028600,1yKAqZoi8xWGLCf5vajroL,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1171,0.928,95.594,0.579,punk,-4.344,0.1800,0.8820,blink-182,four,0.0411,...,0.000000,3nHpBmW5wJXGeC3ojBkpey,1,0,171533,0.000715,1fJFuvU2ldmeAm5nFIHcPP,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1172,0.842,162.011,0.494,punk,-4.784,0.1220,0.5740,Fall Out Boy,four,0.0843,...,0.000000,5nkUSlIhtoJZMOUlB0sNCp,1,7,229093,0.005790,2TfSHkHiFO4gRztVIkggkE,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1173,0.961,114.451,0.621,punk,-3.198,0.0854,0.4490,Fall Out Boy,four,0.1540,...,0.000000,5nkUSlIhtoJZMOUlB0sNCp,0,11,180267,0.005230,0a7BloCiNzLDD9qSQHh5m7,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1174,0.959,193.144,0.409,punk,-4.563,0.0766,0.8300,blink-182,four,0.0869,...,0.000000,3nHpBmW5wJXGeC3ojBkpey,1,9,171600,0.000324,2ydUT1pFhuLDnouelIv4WH,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1175,0.827,167.086,0.290,punk,-3.451,0.3010,0.4500,Green Day,four,0.0362,...,0.000003,5dN7F9DV0Qg1XRdIgW8rke,1,8,493400,0.000659,0MsrWnxQZxPAcov7c74sSo,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1176,0.775,136.020,0.520,punk,-5.803,0.3640,0.3830,blink-182,four,0.0348,...,0.000000,652N05EcNH1a4bIlUixQE2,1,0,249627,0.034000,6xpDh0dXrkVp0Po1qrHUd8,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1177,0.965,112.363,0.403,punk,-2.238,0.3410,0.4310,"Pierce The Veil, Kellin Quinn",four,0.0964,...,0.000276,661Hz0qJK8WIp7vAWsqKvk,1,6,236293,0.000038,1IT0WQk5J8NsaeII8ktdlZ,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju
1178,0.925,159.989,0.472,punk,-3.545,0.0826,0.3380,Pierce The Veil,four,0.1500,...,0.000528,661Hz0qJK8WIp7vAWsqKvk,0,6,267867,0.000394,23UoI3jlFiWdo5jadUYo69,pop punk,audio_features,72GgLgQ63eUHG3CyCv42Ju

In [57]:
df_grp = df.groupby(['playlist_genre','playlist_subgenre'])

In [58]:
df_grp.get_group(('pop','mainstream'))

,energy,tempo,danceability,playlist_genre,loudness,liveness,valence,track_artist,time_signature,speechiness,...,instrumentalness,track_album_id,mode,key,duration_ms,acousticness,id,playlist_subgenre,type,playlist_id
0,0.592,157.969,0.521,pop,-7.777,0.1220,0.535,"Lady Gaga, Bruno Mars",three,0.0304,...,0.000000,10FLjwfpbxLmW8c25Xyc2N,0,6,251668,0.308000,2plbrEY59IikOBgBGLjaoe,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
1,0.507,104.978,0.747,pop,-10.171,0.1170,0.438,Billie Eilish,four,0.0358,...,0.060800,7aJuG4TFXa2hmE4z1yxc3n,1,2,210373,0.200000,6dOtVTDdiauQNBQEDOtlAB,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
2,0.808,108.548,0.554,pop,-4.169,0.1590,0.372,Gracie Abrams,four,0.0368,...,0.000000,0hBRqPYPXhr1RkTDG3n4Mk,1,1,166300,0.214000,7ne4VBA60CxGM75vw0EYad,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
3,0.910,112.966,0.670,pop,-4.070,0.3040,0.786,Sabrina Carpenter,four,0.0634,...,0.000000,4B4Elma4nNDUyl6D5PvQkj,0,0,157280,0.093900,1d7Ptw3qYcfpdLNL5REhtJ,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
4,0.783,149.027,0.777,pop,-4.477,0.3550,0.939,"ROSÉ, Bruno Mars",four,0.2600,...,0.000000,2IYQwwgxgOIn7t3iF6ufFD,0,0,169917,0.028300,5vNRhkKd0yEAg8suGBpjeY,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
5,0.582,116.712,0.700,pop,-5.960,0.0881,0.785,Chappell Roan,four,0.0356,...,0.000000,1WAjjRMfZjEXtB0lQrAw6Q,0,11,218424,0.050200,0WbMK4wrZ1wFSty9F7FCgu,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
6,0.561,150.069,0.669,pop,-6.538,0.0954,0.841,Addison Rae,four,0.0411,...,0.009620,0XA403JTounqFh2owquBXu,1,10,169698,0.495000,6MzofobZt2dm0Kf1hTThFz,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
7,0.247,148.101,0.467,pop,-12.002,0.1700,0.126,Billie Eilish,four,0.0431,...,0.000271,7aJuG4TFXa2hmE4z1yxc3n,0,6,261467,0.612000,3QaPy1KgI7nu9FJEQUgn6h,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
8,0.416,94.926,0.492,pop,-10.439,0.2030,0.297,Gigi Perez,four,0.0254,...,0.000086,4DWrYvfGXRE8ko5ZxlIpit,1,11,211979,0.686000,0UYnhUfnUj5adChuAXvLUB,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
9,0.722,119.973,0.769,pop,-5.485,0.1110,0.570,"The Weeknd, Playboi Carti",four,0.0507,...,0.000003,2IRxVVqbSbqHJo8Zx50LYn,0,11,256000,0.058400,1Es7AUAhQvapIcoh3qMKDL,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
10,0.667,130.019,0.776,pop,-6.622,0.0761,0.618,"Charli xcx, Billie Eilish",four,0.0983,...,0.300000,3ThlxfLSy4bfKzxWqmC7VN,1,7,145219,0.014600,3WOhcATHxK2SLNeP5W3v1v,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
11,0.586,107.071,0.669,pop,-6.073,0.1040,0.579,Sabrina Carpenter,four,0.0540,...,0.000000,5bBaoign62r1i7OV8w7mi9,1,9,186365,0.274000,5N3hjp1WNayUPZrA8kJmJP,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
12,0.806,104.032,0.608,pop,-3.443,0.1910,0.587,Tate McRae,four,0.0486,...,0.000000,2BdJwrx2wMJi7x06wWkUFg,1,1,181821,0.121000,1f18HzFpegqvH4ibGJyeMJ,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
13,0.709,81.012,0.722,pop,-4.950,0.0804,0.604,Shaboozey,four,0.0273,...,0.000000,6egBeCLeGITzGSo5VyRjwZ,1,9,171292,0.063300,2FQrifJ1N335Ljm3TjTVVf,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
14,0.757,139.982,0.742,pop,-4.981,0.3050,0.957,Chappell Roan,four,0.0421,...,0.000000,0EiI8ylL0FmWWpgHVTsZjZ,1,6,184841,0.018700,4xdBrk0nFZaP54vvZj0yx7,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
15,0.917,100.987,0.562,pop,-2.768,0.4880,0.501,Lady Gaga,four,0.1170,...,0.000000,52BWvTRMsPqjHzrbQomgwP,0,11,229997,0.051300,19KlZwqlT3fguP2BeHF1Q1,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
16,0.787,109.939,0.734,pop,-3.951,0.3120,0.672,LISA,four,0.1160,...,0.000000,1OGxb1Z5KDBVOwDtyKu8wz,0,5,155757,0.126000,5G345YEhvleYxQLfYUlEFv,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
17,0.843,122.064,0.619,pop,-5.348,0.1640,0.746,Morgan Wallen,four,0.0284,...,0.000118,0TxewlKVKdpP18dGg279ep,0,5,204829,0.009480,7hR22TOX3RorxJPcsz5Wbo,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
18,0.406,115.940,0.530,pop,-7.507,0.1330,0.338,Gracie Abrams,three,0.0330,...,0.000000,56bdWeO40o3WfAD2Lja4dl,1,10,157147,0.656000,51rfRCiUSvxXlCSCfIztBy,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
19,0.782,119.992,0.727,pop,-8.529,0.2250,0.655,"Adam Port, Stryv, Keinemusik, Orso, Malachiii",four,0.0420,...,0.336000,4M8ThNHbNjda2cPwL8XZHS,0,8,177599,0.056300,1BJJbSX6muJVF2AK7uH1x4,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
20,0.812,80.090,0.505,pop,-3.986,0.4440,0.664,"Tyler, The Creator, GloRilla, Sexyy Red, Lil W...",four,0.4610,...,0.000000,0U28P0QVB1QRxpqp5IHOlH,1,1,255916,0.285000,3tFed7YsjGnIfxeLEQwx3R,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
21,0.760,103.969,0.701,pop,-5.478,0.1850,0.690,Sabrina Carpenter,four,0.0285,...,0.000065,5quMTd5zeI9yW5UDua8wS4,1,0,175459,0.107000,2qSkIjg1o9h3YT9RAgYN75,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
22,0.725,116.988,0.894,pop,-4.984,0.0815,0.838,JENNIE,four,0.0432,...,0.000012,3e5tDT1kfaAGx10yOjIDgW,0,10,136627,0.004340,2CspwnypzT7rcWI9RfsoSb,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
23,0.563,105.008,0.833,pop,-5.593,0.1390,0.343,"Rauw Alejandro, Bad Bunny",four,0.2040,...,0.000013,0aX0UXrHG2ceYIxTQcqJdA,0,4,182857,0.528000,0l0vcZMU7AOeQmUIREoI2U,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
24,0.628,119.980,0.757,pop,-6.715,0.2210,0.321,Don Toliver,four,0.1010,...,0.020900,0Kzb3u6kMnOJOZXYFSk33F,0,4,217333,0.189000,2c7z5oRcPBbqRaBY2mLWcf,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
25,0.855,127.986,0.638,pop,-4.860,0.2450,0.731,"Post Malone, Morgan Wallen",four,0.0264,...,0.000000,1woYXxyyxTQJ0E0AhZE6mj,1,7,178206,0.007570,7221xIgOnuakPdLqT0F3nP,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
26,0.620,117.038,0.741,pop,-5.505,0.0398,0.934,Hozier,four,0.0412,...,0.000809,1KZC0cX0qq6hodR9YVgh9F,1,10,251424,0.029500,4IadxL6BUymXlh8RCJJu7T,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
27,0.339,97.989,0.705,pop,-10.612,0.1200,0.457,The Marías,four,0.0278,...,0.081400,03guxdOi12XJbnvxvxbpwG,1,7,236907,0.552000,3siwsiaEoU4Kuuc9WKMUy5,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
28,0.651,112.648,0.694,pop,-6.968,0.0787,0.471,"Oscar Maydon, Fuerza Regida",three,0.0784,...,0.000014,60cQzWfmdg4hyDXrpW6kOA,1,6,225881,0.496000,1cOboCuWYI2osTOfolMRS6,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
29,0.601,123.994,0.635,pop,-6.129,0.1100,0.332,Myles Smith,four,0.0295,...,0.000000,3VNxRarx9HUI5w7DHv0TBj,0,1,172533,0.246000,3Vr3zh0r7ALn8VLqCiRR10,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
30,0.691,167.029,0.836,pop,-4.222,0.2820,0.703,"GloRilla, Sexyy Red",four,0.3630,...,0.000000,2PzoiaGTcK3NfnMgHFd7QC,1,1,149461,0.005860,4VI2Y5xg4gYynQqNQNQbTN,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
31,0.646,115.842,0.645,pop,-8.334,0.0740,0.295,Ariana Grande,four,0.0427,...,0.000030,71PfP4E9roOXAudea1aPGw,1,5,228639,0.061500,46kspZSY3aKmwQe7O77fCC,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
32,0.471,105.029,0.472,pop,-5.692,0.1400,0.219,Benson Boone,three,0.0603,...,0.000000,29aSKB1qPEbN0Qf9OPSQpw,1,10,180304,0.151000,6tNQ70jh4OwmPGpYy6R2o9,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
33,0.709,194.055,0.744,pop,-5.778,0.0847,0.712,"Myke Towers, benny blanco",four,0.2840,...,0.000000,3pkIK8SI5mcUUjb9jNjx4H,0,6,130880,0.050100,0qeIFEGRQqHoaJtLCl0U73,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
34,0.904,167.033,0.739,pop,-2.655,0.0948,0.788,KATSEYE,four,0.0442,...,0.000010,1hjqg3TuQ2YqooaPhxHwdv,0,5,129883,0.549000,6aJn7Cst74cj4lNIiPRgav,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
35,0.604,159.920,0.561,pop,-4.409,0.1040,0.242,Teddy Swims,three,0.0337,...,0.000019,7nacKlk586eLRBSIsrk9DB,1,9,210689,0.199000,17phhZDn6oGtzMe56NuWvj,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
36,0.668,90.969,0.646,pop,-5.203,0.2120,0.640,Mark Ambor,four,0.0282,...,0.000000,3PlCMwyq6nuQYtoYproV1o,1,2,148318,0.491000,5uQ7de4EWjb3rkcFxyEOpu,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
37,0.668,128.027,0.924,pop,-6.795,0.0678,0.787,KAROL G,four,0.0469,...,0.000594,5ylbxH7EqpsmHZCRuiYewS,1,11,195824,0.446000,6WatFBLVB0x077xWeoVc2k,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
38,0.454,159.982,0.689,pop,-7.643,0.0707,0.912,Djo,four,0.0584,...,0.002590,4JDXBZdRPId4devseaAOKH,1,2,159246,0.035100,3qhlB30KknSejmIvZZLjOD,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
39,0.386,192.004,0.504,pop,-10.976,0.0961,0.281,"Taylor Swift, Post Malone",four,0.0308,...,0.000015,1Mo4aZ8pdj6L1jx8zSwJnt,1,11,228965,0.502000,2OzhQlSqBEmt7hmkYxfT6m,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
40,0.681,155.079,0.560,pop,-6.304,0.1060,0.388,"Omar Courtz, De La Rose",four,0.2440,...,0.000000,3C5uwdRE5QRoXSGPPxpDd4,0,6,223320,0.103000,0Sr7ssScx54yxdM2ols7nW,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
41,0.472,101.061,0.898,pop,-7.001,0.1410,0.214,Kendrick Lamar,four,0.0776,...,0.000000,5JjnoGJyOxfSZUZtk2rRwZ,1,1,274192,0.010700,6AI3ezQ4o3HUoP6Dhudph3,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
42,0.711,146.921,0.487,pop,-4.220,0.1520,0.317,Jin,four,0.0322,...,0.000000,0fKlaQuBMQYFo5aIFoGIXt,1,8,151647,0.000175,4p7DTkyrKqT98xlIwYYfXz,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
43,0.712,91.980,0.848,pop,-3.574,0.1060,0.692,"KAROL G, Feid, DFZM, Ovy On The Drums, J Balvi...",four,0.0981,...,0.000000,5TT8KluomuelzsNF7T1U37,0,1,298131,0.221000,3mg9jYNC1NihbthlglzrWP,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
44,0.645,114.933,0.882,pop,-7.233,0.0570,0.788,Ndotz,four,0.0601,...,0.000041,0mV9Pfr1GfoZLkp1EAau9P,1,1,104419,0.475000,0io16MKpbeDIdYzmGpQaES,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
45,0.872,184.115,0.466,pop,-3.344,0.1210,0.806,Linkin Park,four,0.0336,...,0.000000,6W0Gabv5f3ugnckc6YgfJQ,1,7,190428,0.015600,2PnlsTsOTLE5jnBnNe2K0A,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M
46,0.756,116.034,0.660,pop,-3.743,0.1930,0.838,Jimin,four,0.0320,...,0.000000,15XcLhiVMlSOipUddTNDnr,0,0,170888,0.002890,7tI8dRuH2Yc6RuoTjxo4dU,mainstream,audio_features,37i9dQZF1DXcBWIGoYBM5M

# joining data frames

In [200]:
reg = {'Roll_No':[1,2,3],'Name':['Emmanual',"ikku","anjusha"]}
df1 = pd.DataFrame(reg)
df1

   Roll_No      Name
0        1  Emmanual
1        2      ikku
2        3   anjusha

In [202]:
data = {"Roll_No":[4,5,6,],'Name':['Kevin',"Ivan","Godson"]}
df2 = pd.DataFrame(data)
df2

   Roll_No    Name
0        4   Kevin
1        5    Ivan
2        6  Godson

In [206]:
df3 = pd.concat([df1,df2],ignore_index=True)
df3

   Roll_No      Name
0        1  Emmanual
1        2      ikku
2        3   anjusha
3        4     Kevin
4        5      Ivan
5        6    Godson

In [208]:
email = ["emmanualmenoth@gmail.com","ikkumenoth@gmail.com","anjushwilson@gmail.com","kevinjose@gmail.com","ivanboss@gmail.com","godsonnotes@gmail.com"]
email

['emmanualmenoth@gmail.com',
 'ikkumenoth@gmail.com',
 'anjushwilson@gmail.com',
 'kevinjose@gmail.com',
 'ivanboss@gmail.com',
 'godsonnotes@gmail.com']

In [210]:
ser = pd.Series(email,name ="email")
ser

0    emmanualmenoth@gmail.com
1        ikkumenoth@gmail.com
2      anjushwilson@gmail.com
3         kevinjose@gmail.com
4          ivanboss@gmail.com
5       godsonnotes@gmail.com
Name: email, dtype: object

In [212]:
df4 = pd.concat([df3,ser],axis=1)
df4

   Roll_No      Name                     email
0        1  Emmanual  emmanualmenoth@gmail.com
1        2      ikku      ikkumenoth@gmail.com
2        3   anjusha    anjushwilson@gmail.com
3        4     Kevin       kevinjose@gmail.com
4        5      Ivan        ivanboss@gmail.com
5        6    Godson     godsonnotes@gmail.com

In [218]:
# merging dataframe

data1 = {"Roll_No":[1,2,3,4,5,6,],'place':['chalakudy',"west chalakudy","west chalakudy","chalakudy","kochi","kochi"]}
df5 = pd.DataFrame(data1)
df5

   Roll_No           place
0        1       chalakudy
1        2  west chalakudy
2        3  west chalakudy
3        4       chalakudy
4        5           kochi
5        6           kochi

In [220]:
df6 = pd.merge(df4,df5,on="Roll_No")
df6

   Roll_No      Name                     email           place
0        1  Emmanual  emmanualmenoth@gmail.com       chalakudy
1        2      ikku      ikkumenoth@gmail.com  west chalakudy
2        3   anjusha    anjushwilson@gmail.com  west chalakudy
3        4     Kevin       kevinjose@gmail.com       chalakudy
4        5      Ivan        ivanboss@gmail.com           kochi
5        6    Godson     godsonnotes@gmail.com           kochi